# Generated by Django 3.0.8 on 2020-11-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainNumber', models.IntegerField(help_text='Train number should be of 4-5 characters and should be unique', primary_key=True, serialize=False)),
                ('starts', models.CharField(max_length=20)),
                ('ends', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateField()),
                ('departureTime', models.TimeField()),
                ('AcNumber', models.IntegerField()),
                ('SlNumber', models.IntegerField()),
                ('releasedDate', models.DateField()),
                ('releasedTime', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='released_trains', to='rail.Train')),
            ],
        ),
    ]
