# Generated by Django 3.0.8 on 2020-11-25 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berthNumber', models.IntegerField()),
                ('coachType', models.CharField(choices=[('SL', 'Sleeper'), ('AC', 'AC')], max_length=2)),
                ('berthType', models.CharField(choices=[('LB', 'LB'), ('UB', 'UB'), ('MB', 'MB'), ('SL', 'SL'), ('SU', 'SU')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAgent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('creditCardNo', models.BigIntegerField(unique=True)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachType', models.CharField(choices=[('SL', 'Sleeper'), ('AC', 'AC')], max_length=2)),
                ('coachNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.BigIntegerField(default=100000000000, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainNumber', models.IntegerField(help_text='Train number should be of 4-5 characters and should be unique', primary_key=True, serialize=False)),
                ('starts', models.CharField(max_length=20)),
                ('ends', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Berth')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateField()),
                ('departureTime', models.TimeField()),
                ('maxAC', models.IntegerField()),
                ('maxSL', models.IntegerField()),
                ('currAC', models.IntegerField()),
                ('currSL', models.IntegerField()),
                ('releasedDate', models.DateField()),
                ('releasedTime', models.TimeField()),
                ('fareAC', models.IntegerField(default=100)),
                ('fareSL', models.IntegerField(default=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='released_trains', to='rail.Train', verbose_name='Train Number')),
            ],
        ),
        migrations.CreateModel(
            name='Pnr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.BookingAgent')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='releasedTrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.ReleasedTrain'),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Passenger')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Pnr')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Seat')),
            ],
        ),
    ]
