# Generated by Django 3.0.8 on 2020-11-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedtrain',
            name='AcNumber',
            field=models.IntegerField(verbose_name='Number of AC coaches'),
        ),
        migrations.AlterField(
            model_name='releasedtrain',
            name='SlNumber',
            field=models.IntegerField(verbose_name='Number of Sleepers'),
        ),
        migrations.AlterField(
            model_name='releasedtrain',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='released_trains', to='rail.Train', verbose_name='Train Number'),
        ),
    ]
