# Generated by Django 3.0.8 on 2020-11-21 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('rail', '0002_auto_20201120_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAgent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('creditCardNo', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='releasedtrain',
            name='AcNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='releasedtrain',
            name='SlNumber',
            field=models.IntegerField(),
        ),
    ]
