# Generated by Django 3.0.8 on 2020-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0003_auto_20201122_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingagent',
            name='creditCardNo',
            field=models.BigIntegerField(unique=True),
        ),
    ]
