# Generated by Django 3.0.8 on 2020-11-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0007_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
